//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benavides.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BenavidesBIEntities : DbContext
    {
        public BenavidesBIEntities()
            : base("name=BenavidesBIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblLaboratorio> tblLaboratorio { get; set; }
        public virtual DbSet<tblSegmento> tblSegmento { get; set; }
        public virtual DbSet<tblPromocionesAcumulacion> tblPromocionesAcumulacion { get; set; }
    }
}
