//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benavides.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPromocionesAcumulacion
    {
        public int idPromocionAcumulacion { get; set; }
        public Nullable<int> codigo { get; set; }
        public string producto { get; set; }
        public string promocion { get; set; }
        public string regla { get; set; }
        public string limite { get; set; }
        public string periodo { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public Nullable<System.DateTime> cupon { get; set; }
        public string comentario { get; set; }
        public int idSegmento { get; set; }
        public int idLaboratorio { get; set; }
        public string codigoRegala { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
    
        public virtual tblLaboratorio tblLaboratorio { get; set; }
        public virtual tblSegmento tblSegmento { get; set; }
    }
}
